# Generated by Django 5.0.3 on 2024-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptiontest', '0002_imageobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobject',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
    ]
