# Generated by Django 5.0.3 on 2024-03-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptiontest', '0003_alter_imageobject_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_angle', models.IntegerField(blank=True, null=True)),
                ('object1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_object1', to='perceptiontest.imageobject')),
                ('object2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_object2', to='perceptiontest.imageobject')),
                ('object3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_object3', to='perceptiontest.imageobject')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DurationField()),
                ('user_angle', models.IntegerField()),
                ('correct_angle', models.IntegerField()),
                ('test_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perceptiontest.testtaker')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perceptiontest.question')),
            ],
        ),
    ]
