# Generated by Django 5.0.3 on 2024-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptiontest', '0004_alter_testtaker_email_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
