# Generated by Django 5.0.3 on 2024-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptiontest', '0008_testtakerquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='TestTakerQuestion',
        ),
    ]
